spring:
  application:
    name: artist-service-api
  datasource:
    url: jdbc:postgresql://localhost:5432/artistsdb
    username: fullstack
    password: password01!
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

server:
  error:
    include-message: always
  port: 8181

logging:
  level:
    org:
      hibernate:
        sql: debug
      type:
        descriptor:
          sql:
            BasicBinder: trace

artist:
  resource:
    api:
      url: https://api.discogs.com/
      name: discogs-api