spring:
  application:
    name: artist-service-api
  datasource:
    url: jdbc:postgresql://postgres-docker-db:5432/artistsdb
    username: demouserdb
    password: password01!
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  error:
    include-message: never
  port: 9191

logging:
  level:
    org:
      hibernate:
        sql: warn
